name: MattBurkett
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34795399685390294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#f5dcbe'
    - '#2d2d2d'
    - '#675758'
    - '#88c6f2'
  brandStrength: 0.5
  lightness: 0.06552623677998781
  saturation: 0
  rhythmicContrast: 1
purpose: []
