name: MattBurkett
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#576e42'
    - '#1d241c'
    - '#91af59'
    - '#d7d7d7'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
